# --- DNK-MRH-HEADER ---
# mrh_id: "dockerfile_security_sandbox"
# purpose: "Minimal hardened Dockerfile for DNK OS Plugin Sandbox"
# author: "DNK-e.com Maksym"
# license: "MIT"
# status: "Active"
# version: "1.1.0"
# updated_at: "2026-08-15"
# --- END DNK-MRH-HEADER ---

FROM python:3.12-slim
WORKDIR /app
RUN groupadd -g 10001 sandboxgroup && useradd -u 10001 -g sandboxgroup -m -s /bin/bash sandboxuser
USER 10001:10001
CMD ["python3"]
